### ISSUE TITLE
Change config settings to be saved in config_plugins table instead of config table

### ISSUE THREAD

**Issue by kristian-94** [catalyst/moodle-metadataextractor_tika#3]
Storing the config settings for the plugin in the main config table seems wrong, they probably should use the same convention as for example datacleaner sub plugins that get their settings saved in the config_plugins table. 

https://github.com/catalyst/moodle-local_datacleaner/blob/master/cleaner/delete_users/settings.php#L30

**Comment by tomdickman** [comment]
Resolved in #6
